/**
 * End-to-end tests for <pii-redactor>.
 *
 * These tests run in a real browser via Playwright and exercise the full
 * pipeline: image upload → OCR → NER → SVG overlay → export.
 *
 * IMPORTANT: The first run downloads the NER model (~80MB). Subsequent runs
 * use the browser cache. Set the SKIP_MODEL_DOWNLOAD env var to skip tests
 * that require model inference (for fast CI pre-flight checks).
 *
 * Performance design
 * ──────────────────
 * OCR (Tesseract WASM init + recognition) and NER (Transformers.js inference)
 * are the expensive steps — each takes several seconds even with a warm cache.
 * To avoid re-running them for every assertion, each pipeline describe block
 * shares a single browser page via beforeAll: the image is uploaded once, the
 * pipeline runs to "reviewing", and all read-only assertions in that block
 * inspect the already-resolved state.
 *
 * Tests that mutate component state (confirm, cancel, toggle) need a clean
 * component, so they open their own page and upload independently.
 */

import { test, expect, type Page, type Browser } from "@playwright/test";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEMO_URL = process.env.DEMO_URL ?? "/demo/";
const TEST_IMAGE = path.resolve(__dirname, "../../demo/test-screenshot.png");

// Fixture images covering a range of real-world upload scenarios.
// Generated by: tests/e2e/fixtures/generate-fixtures.sh
const FIXTURES = {
  /** White-background chat (ChatGPT / Claude light theme). */
  lightModeChat: path.resolve(__dirname, "fixtures/light-mode-chat.png"),
  /** Screenshot with zero PII — pipeline should produce 0 redactions. */
  noPii: path.resolve(__dirname, "fixtures/no-pii.png"),
  /** Structured PII only: SSN, credit card, IP, URL — regex branch. */
  regexOnly: path.resolve(__dirname, "fixtures/regex-only.png"),
  /** Low-resolution mobile screenshot (390×280). */
  smallMobile: path.resolve(__dirname, "fixtures/small-mobile.png"),
  /** 2× high-DPI retina screenshot (1600×1000). */
  hidpi: path.resolve(__dirname, "fixtures/hidpi.png"),
  /** JPEG with quality-60 compression artifacts. */
  jpegArtifact: path.resolve(__dirname, "fixtures/jpeg-artifact.jpg"),
  /** WebP format upload. */
  webpFormat: path.resolve(__dirname, "fixtures/webp-format.webp"),
  /** Long email addresses near line-wrap boundaries. */
  multilineEmail: path.resolve(__dirname, "fixtures/multiline-email.png"),
  /** Two-column Slack-style layout (sidebar + message area). */
  slackStyle: path.resolve(__dirname, "fixtures/slack-style.png"),
  /** 1×1 white PNG — used where only a phase transition needs to be observed,
   *  not pipeline output. OCR returns empty text almost instantly. */
  minimal: path.resolve(__dirname, "fixtures/minimal.png"),
};

// ── Helpers ───────────────────────────────────────────────────────────────────

// Get a property directly off the <pii-redactor> element
async function shadowProp(page: Page, selector: string): Promise<unknown> {
  return page.evaluate((sel) => {
    const el = document.querySelector("pii-redactor") as any;
    return el?.[sel];
  }, selector);
}

// Wait for the component to reach a given phase
async function waitForPhase(page: Page, phase: string, timeout = 240_000) {
  await page.waitForFunction(
    (p) => {
      const el = document.querySelector("pii-redactor") as any;
      return el?.phase === p;
    },
    phase,
    { timeout },
  );
}

// Wait for idle phase (used in beforeAll/beforeEach helpers)
async function waitForIdle(page: Page) {
  await page.waitForSelector("pii-redactor");
  await page.waitForFunction(() => {
    const el = document.querySelector("pii-redactor") as any;
    return el?.phase === "idle";
  });
}

// Get the text content of a shadow DOM element
async function shadowText(page: Page, cssSelector: string): Promise<string> {
  return page.evaluate((sel) => {
    const host = document.querySelector("pii-redactor");
    if (!host?.shadowRoot) return "";
    return host.shadowRoot.querySelector(sel)?.textContent?.trim() ?? "";
  }, cssSelector);
}

// Upload a file via the dropzone and wait for the reviewing phase
async function uploadAndReview(page: Page, imagePath: string) {
  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    page.evaluate(() => {
      document
        .querySelector("pii-redactor")
        ?.shadowRoot?.querySelector<HTMLElement>(".dropzone")
        ?.click();
    }),
  ]);
  await fileChooser.setFiles(imagePath);
  await waitForPhase(page, "reviewing");
}

// Count redaction boxes in the SVG overlay
async function countRedactionBoxes(page: Page): Promise<number> {
  return page.evaluate(() => {
    const host = document.querySelector("pii-redactor");
    const svgs = host?.shadowRoot?.querySelectorAll("svg");
    if (!svgs) return 0;
    for (const svg of svgs) {
      const rects = svg.querySelectorAll("rect.redaction-box");
      if (rects.length > 0) return rects.length;
    }
    return 0;
  });
}

// Open a fresh page, navigate to the demo, and upload an image to reviewing.
// Returns the page — caller is responsible for closing it.
async function openReviewingPage(browser: Browser, imagePath: string): Promise<Page> {
  const page = await browser.newPage();
  await page.goto(DEMO_URL);
  await waitForIdle(page);
  await uploadAndReview(page, imagePath);
  return page;
}

// ── Setup: non-pipeline tests ─────────────────────────────────────────────────
// The global beforeEach only runs for tests outside a describe block that
// manages its own page lifecycle.

test.beforeEach(async ({ page }) => {
  await page.goto(DEMO_URL);
  await waitForIdle(page);
});

// ── Trust layer ───────────────────────────────────────────────────────────────

test("trust banner is visible and shows privacy message", async ({ page }) => {
  const bannerText = await shadowText(page, ".trust-banner");
  expect(bannerText).toContain("Your data never leaves your device");
});

// ── File upload ───────────────────────────────────────────────────────────────

test("drop zone is visible in idle state", async ({ page }) => {
  const dropzoneVisible = await page.evaluate(() => {
    const host = document.querySelector("pii-redactor");
    return !!host?.shadowRoot?.querySelector(".dropzone");
  });
  expect(dropzoneVisible).toBe(true);
});

test("uploading an invalid file type shows an error", async ({ page }) => {
  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    page.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      host?.shadowRoot?.querySelector<HTMLElement>(".dropzone")?.click();
    }),
  ]);

  const tmpFile = path.resolve(__dirname, "../../demo/test.txt");
  await import("fs").then((fs) => fs.writeFileSync(tmpFile, "not an image"));
  await fileChooser.setFiles(tmpFile);

  await page.waitForFunction(() => {
    const host = document.querySelector("pii-redactor") as any;
    return host?.errorMessage?.includes("Unsupported") || host?.errorMessage?.length > 0;
  }, { timeout: 5_000 });

  const error = await shadowText(page, ".error");
  expect(error).toBeTruthy();
});

// ── Full pipeline — shared page ───────────────────────────────────────────────
//
// One upload drives all read-only assertions in this block.
// Mutating tests (confirm, cancel, toggle) manage their own page.

test.describe("pipeline tests (requires model download)", () => {
  test.setTimeout(300_000);

  // Shared reviewing-phase page — upload runs once in beforeAll.
  let sharedPage: Page;

  test.beforeAll(async ({ browser }) => {
    sharedPage = await openReviewingPage(browser, TEST_IMAGE);
  });

  test.afterAll(async () => {
    await sharedPage.close();
  });

  test("uploading a screenshot starts the loading phase", async ({ page }) => {
    // Only needs to observe the phase transition away from idle — not pipeline
    // output. Use a 1×1 minimal image so OCR finishes near-instantly and the
    // full pipeline doesn't run unnecessarily in the background.
    const [fileChooser] = await Promise.all([
      page.waitForEvent("filechooser"),
      page.evaluate(() => {
        document.querySelector("pii-redactor")?.shadowRoot
          ?.querySelector<HTMLElement>(".dropzone")?.click();
      }),
    ]);
    await fileChooser.setFiles(FIXTURES.minimal);

    await page.waitForFunction(() => {
      const el = document.querySelector("pii-redactor") as any;
      return el?.phase !== "idle";
    }, { timeout: 10_000 });

    const phase = await shadowProp(page, "phase");
    expect(["loading", "ocr", "detecting", "reviewing"]).toContain(phase);
  });

  test("pipeline reaches reviewing phase and renders SVG redaction boxes", async () => {
    const rectCount = await countRedactionBoxes(sharedPage);
    expect(rectCount).toBeGreaterThan(0);
  });

  test("entity list shows detected items", async () => {
    const headerText = await sharedPage.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      if (!host?.shadowRoot) return "";
      const el = host.shadowRoot.querySelector(".entity-list-header") as HTMLElement | null;
      return el?.innerText?.replace(/\s+/g, " ").trim() ?? "";
    });
    expect(headerText).toMatch(/Detected items \(\d+ \/ \d+\)/);
    const [enabled, total] = headerText.match(/\d+/g)!.map(Number);
    expect(total).toBeGreaterThan(0);
    expect(enabled).toBe(total);
  });

  test("user can toggle a redaction off via the entity list", async ({ browser }) => {
    // Mutates component state — needs its own fresh reviewing page.
    const page = await openReviewingPage(browser, TEST_IMAGE);
    try {
      await page.evaluate(() => {
        const host = document.querySelector("pii-redactor");
        host?.shadowRoot
          ?.querySelector<HTMLInputElement>(".entity-item input[type=checkbox]")
          ?.click();
      });
      await page.waitForTimeout(300);

      const headerText = await shadowText(page, ".entity-list-header");
      const [enabled, total] = headerText.match(/\d+/g)!.map(Number);
      expect(enabled).toBe(total - 1);
    } finally {
      await page.close();
    }
  });

  test("confirm & redact produces a redaction-complete event with a PNG blob", async ({
    browser,
  }) => {
    // Mutates component state (transitions to done) — needs its own page.
    const page = await openReviewingPage(browser, TEST_IMAGE);
    try {
      let eventFired = false;
      let blobSize = 0;

      await page.exposeFunction("onRedactionComplete", (size: number) => {
        eventFired = true;
        blobSize = size;
      });
      await page.evaluate(() => {
        document.querySelector("pii-redactor")?.addEventListener(
          "redaction-complete",
          (e: any) => (window as any).onRedactionComplete(e.detail.blob.size),
        );
      });

      await page.evaluate(() => {
        const host = document.querySelector("pii-redactor");
        host?.shadowRoot?.querySelector<HTMLElement>("button.primary")?.click();
      });

      await page.waitForFunction(() => (window as any).__redactionDone, {
        timeout: 30_000,
      });
      expect(eventFired).toBe(true);
      expect(blobSize).toBeGreaterThan(1000);
    } finally {
      await page.close();
    }
  });

  test("cancel button fires redaction-cancel and resets to idle", async ({ browser }) => {
    // Mutates component state (transitions to idle) — needs its own page.
    const page = await openReviewingPage(browser, TEST_IMAGE);
    try {
      let cancelFired = false;
      await page.exposeFunction("onRedactionCancel", () => { cancelFired = true; });
      await page.evaluate(() => {
        document.querySelector("pii-redactor")?.addEventListener(
          "redaction-cancel",
          () => (window as any).onRedactionCancel(),
        );
      });

      await page.evaluate(() => {
        const host = document.querySelector("pii-redactor");
        host?.shadowRoot?.querySelector<HTMLElement>("button.danger")?.click();
      });

      await page.waitForFunction(
        () => { const el = document.querySelector("pii-redactor") as any; return el?.phase === "idle"; },
        { timeout: 5_000 },
      );

      expect(cancelFired).toBe(true);
      const phase = await shadowProp(page, "phase");
      expect(phase).toBe("idle");
    } finally {
      await page.close();
    }
  });
});

// ── Mobile viewport ───────────────────────────────────────────────────────────

test.describe("mobile viewport", () => {
  test("component renders correctly at mobile width", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(DEMO_URL);
    await page.waitForSelector("pii-redactor");

    const dropzoneVisible = await page.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      const dz = host?.shadowRoot?.querySelector(".dropzone");
      if (!dz) return false;
      const rect = dz.getBoundingClientRect();
      return rect.width > 0 && rect.height > 0;
    });
    expect(dropzoneVisible).toBe(true);
  });

  test("trust banner is visible on mobile", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(DEMO_URL);
    await page.waitForSelector("pii-redactor");

    const bannerText = await shadowText(page, ".trust-banner");
    expect(bannerText).toContain("never leaves your device");
  });
});

// ── Image variety tests ───────────────────────────────────────────────────────
//
// Each describe block shares a single reviewing-phase page via beforeAll.
// The image is uploaded once; all assertions in the block inspect that state.
// Tests that need to mutate state (confirm export) open their own page.

test.describe("image variety: light-mode chat (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.lightModeChat);
  });
  test.afterAll(async () => page.close());

  test("light-mode white-background screenshot detects PII", async () => {
    // Simulates a Claude.ai / ChatGPT light-theme screenshot.
    // Contains: name (Alex Rivera), email, phone, dates, username, zip code.
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeGreaterThan(0);
  });

  test("entity list registers detections on light-mode image", async () => {
    const headerText = await page.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      if (!host?.shadowRoot) return "";
      const el = host.shadowRoot.querySelector(".entity-list-header") as HTMLElement | null;
      return el?.innerText?.replace(/\s+/g, " ").trim() ?? "";
    });
    expect(headerText).toMatch(/Detected items \(\d+ \/ \d+\)/);
    const [, total] = headerText.match(/\d+/g)!.map(Number);
    expect(total).toBeGreaterThan(0);
  });
});

test.describe("image variety: no-PII screenshot (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.noPii);
  });
  test.afterAll(async () => page.close());

  test("screenshot with no personal data produces very few redactions", async () => {
    // Contains only factual geography text — no names, emails, phones, addresses.
    // The NER model may still flag incidental years or ordinals (e.g. "10th") as
    // DATE false-positives; we allow up to 2 such hits rather than asserting zero.
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeLessThanOrEqual(2);
  });

  test("entity list header shows very few items on no-PII image", async () => {
    const headerText = await page.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      if (!host?.shadowRoot) return "";
      const el = host.shadowRoot.querySelector(".entity-list-header") as HTMLElement | null;
      return el?.innerText?.replace(/\s+/g, " ").trim() ?? "";
    });
    // Allow 0, 1, or 2 detections — not the 5+ you'd see on a real PII image
    const match = headerText.match(/Detected items \((\d+) \/ (\d+)\)/);
    if (match) {
      expect(Number(match[2])).toBeLessThanOrEqual(2);
    } else {
      // No header rendered at all means zero items — also acceptable
      expect(headerText.length === 0 || /no detected/i.test(headerText)).toBe(true);
    }
  });
});

test.describe("image variety: regex-only PII (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.regexOnly);
  });
  test.afterAll(async () => page.close());

  test("support-ticket screenshot with SSN, credit card, IP, URL is redacted", async () => {
    // Contains: SSN (123-45-6789), credit card (4532 1234 5678 9012),
    // IP (192.168.1.105), URL, email, two phone numbers, date.
    const rectCount = await countRedactionBoxes(page);
    // Expect at least SSN + credit card + IP + email = 4 distinct redactions
    expect(rectCount).toBeGreaterThanOrEqual(4);
  });
});

test.describe("image variety: small mobile screenshot (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.smallMobile);
  });
  test.afterAll(async () => page.close());

  test("low-resolution mobile screenshot reaches reviewing phase", async () => {
    // 390×280 — well below the standard 800×600 fixture.
    const phase = await shadowProp(page, "phase");
    expect(phase).toBe("reviewing");
  });

  test("small mobile screenshot detects PII", async () => {
    // Should have detected name, email, phone, DOB, zip
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeGreaterThan(0);
  });

  test("confirm on small mobile image produces a valid PNG blob", async ({ browser }) => {
    // Mutates component state — needs its own page.
    const ownPage = await openReviewingPage(browser, FIXTURES.smallMobile);
    try {
      let blobSize = 0;
      await ownPage.exposeFunction("onSmallRedactionDone", (size: number) => {
        blobSize = size;
      });
      await ownPage.evaluate(() => {
        document.querySelector("pii-redactor")?.addEventListener(
          "redaction-complete",
          (e: any) => (window as any).onSmallRedactionDone(e.detail.blob.size),
        );
      });

      await ownPage.evaluate(() => {
        const host = document.querySelector("pii-redactor");
        host?.shadowRoot?.querySelector<HTMLElement>("button.primary")?.click();
      });
      await ownPage.waitForFunction(() => (window as any).__redactionDone, {
        timeout: 30_000,
      });
      expect(blobSize).toBeGreaterThan(1000);
    } finally {
      await ownPage.close();
    }
  });
});

test.describe("image variety: high-DPI screenshot (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.hidpi);
  });
  test.afterAll(async () => page.close());

  test("1600×1000 retina screenshot is processed without error", async () => {
    // 2× scale — pipeline must handle large canvas without crashing.
    const phase = await shadowProp(page, "phase");
    expect(phase).toBe("reviewing");
  });

  test("high-DPI screenshot detects PII", async () => {
    // Contains full name, street address, email, phone, SSN, DOB
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeGreaterThan(0);
  });
});

test.describe("image variety: JPEG with compression artifacts (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.jpegArtifact);
  });
  test.afterAll(async () => page.close());

  test("JPEG upload is accepted and pipeline completes", async () => {
    // Quality-60 JPEG — tests MIME-type acceptance and OCR resilience to noise.
    const phase = await shadowProp(page, "phase");
    expect(phase).toBe("reviewing");
  });

  test("JPEG with PII produces redaction boxes", async () => {
    // Contains: name, address, email, DOB, credit card number.
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeGreaterThan(0);
  });
});

test.describe("image variety: WebP format (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.webpFormat);
  });
  test.afterAll(async () => page.close());

  test("WebP file is accepted and pipeline reaches reviewing phase", async () => {
    // WebP is a common format for screenshots on macOS (Safari share sheet).
    const phase = await shadowProp(page, "phase");
    expect(phase).toBe("reviewing");
  });

  test("WebP screenshot detects name, phone, email, DOB", async () => {
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeGreaterThan(0);
  });
});

test.describe("image variety: multiline email addresses (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.multilineEmail);
  });
  test.afterAll(async () => page.close());

  test("long email addresses near line wrap are detected", async () => {
    // Tests the bridge's word-grouping: an email on one line should map to
    // exactly one contiguous bounding box, not two split boxes.
    const rectCount = await countRedactionBoxes(page);
    // Both emails should be detected
    expect(rectCount).toBeGreaterThanOrEqual(2);
  });

  test("no individual redaction box spans nearly the full image width", async () => {
    // A broken multi-line merge would produce a bbox stretching ~100% of width.
    const imageWidth = await page.evaluate(() => {
      const img = document.querySelector("pii-redactor")?.shadowRoot
        ?.querySelector<HTMLImageElement>("img, canvas");
      return img?.clientWidth ?? 800;
    });
    const maxBoxWidth = await page.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      let max = 0;
      for (const svg of host?.shadowRoot?.querySelectorAll("svg") ?? []) {
        for (const rect of svg.querySelectorAll("rect.redaction-box")) {
          const w = parseFloat(rect.getAttribute("width") ?? "0");
          if (w > max) max = w;
        }
      }
      return max;
    });
    expect(maxBoxWidth).toBeGreaterThan(0);
    expect(maxBoxWidth).toBeLessThan(imageWidth * 0.95);
  });
});

test.describe("image variety: two-column Slack layout (requires model download)", () => {
  test.setTimeout(300_000);
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await openReviewingPage(browser, FIXTURES.slackStyle);
  });
  test.afterAll(async () => page.close());

  test("Slack-style sidebar+content layout is processed successfully", async () => {
    // Two-column layout exercises the COLUMN_GAP_THRESHOLD_PX logic in bridge.ts.
    const phase = await shadowProp(page, "phase");
    expect(phase).toBe("reviewing");
  });

  test("Slack screenshot detects PII in the message column", async () => {
    // Contains: email, phone, address, SSN, DOB, IP, credit card in message area.
    const rectCount = await countRedactionBoxes(page);
    expect(rectCount).toBeGreaterThan(0);
  });

  test("no redaction box spans the full width of the image (cross-column guard)", async () => {
    // If the column-gap splitting logic fails, we'd get a single bbox stretching
    // from the sidebar to the message column. Verify no box exceeds 80% width.
    const tooWide = await page.evaluate(() => {
      const host = document.querySelector("pii-redactor");
      const svgViewBox = (() => {
        for (const svg of host?.shadowRoot?.querySelectorAll("svg") ?? []) {
          const rects = svg.querySelectorAll("rect.redaction-box");
          if (rects.length > 0) {
            const vb = svg.getAttribute("viewBox");
            return vb ? parseFloat(vb.split(" ")[2]) : 0;
          }
        }
        return 0;
      })();
      if (svgViewBox === 0) return false;

      const threshold = svgViewBox * 0.80;
      for (const svg of host?.shadowRoot?.querySelectorAll("svg") ?? []) {
        for (const rect of svg.querySelectorAll("rect.redaction-box")) {
          if (parseFloat(rect.getAttribute("width") ?? "0") > threshold) {
            return true;
          }
        }
      }
      return false;
    });
    expect(tooWide).toBe(false);
  });
});
